<?php
# This file was automatically generated by the MediaWiki 1.22alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
   exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "DRMF";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";
$wgArticlePath = "/wiki/$1";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://drmf.mathweb.org";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "/wiki/skins/common/images/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@drmf.mathweb.org";
$wgPasswordSender = "apache@drmf.mathweb.org";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "sqlite";
$wgDBserver = "";
$wgDBname = "drmf_wiki";
$wgDBuser = "";
$wgDBpassword = "";

# SQLite-specific settings
$wgSQLiteDataDir = "/var/www/DRMF/data";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgGenerateThumbnailOnParse = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "6775cceffaa47333dabb4b3cbf97cddc9a548a88a1ab4c408488e2608634ffff";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "f2ffe87ba2b69dd5";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";



# End of automatically generated settings.
# Add more configuration options below.

# Disable caching (for now, Math links need to update)
$wgEnableParserCache = false;
$wgCachePages = false;

# Permissions
# Prevent new user registrations except by sysops
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
# Anonymous users can't create pages
$wgGroupPermissions['*']['createpage'] = false;
# Disable reading by anonymous users
$wgGroupPermissions['*']['read'] = false;
# But allow them to read e.g., these pages:
$wgWhitelistRead =  array ( "Main Page", "Special:Userlogin", "Help:Contents", "-");

# Math extension
require_once("$IP/extensions/Math/Math.php");
$wgUseLaTeXML = true; // enabeling MathJax as rendering option
$wgDefaultUserOptions['math'] = MW_MATH_LATEXML; // setting LaTeXML as default rendering option (optional)
$wgLaTeXMLUrl = 'http://latexml.mathweb.org/convert';
$wgDefaultLaTeXMLSetting = 'mode=math&preload=texvc.sty&preload=DLMFmath.sty&linelength=80';

#MathMenu extension
require_once("$IP/extensions/MathMenu/MathMenu.php");

#Show detailed debugging information
# $wgShowExceptionDetails = true;

# error_reporting( -1 );
# ini_set( 'display_errors', 1 );
#$wgDebugComments = true;
# $wgDebugLogFile = "/tmp/debug_log.txt";
# $wgDebugToolbar = true;

### WMSearch extension
# $wgSearchType = 'LuceneSearch';
# $wgLuceneHost = '127.0.0.1'; #IP address of server
# $wgLucenePort = 8123;
# require_once( "$IP/extensions/MWSearch/MWSearch.php" );
 
# comment this out if you are using the old version 2.0
# (MUST be AFTER the require_once!)
# $wgLuceneSearchVersion = 2.1;


### MathWebSearch extension
#require_once "$IP/extensions/MathSearch/MathSearch.php";
#$wgMWSUrl = 'http://drmf.mathweb.org:9090';
